applications:
  app:
    type: python:3.9

    web:
      commands:
        start: "gunicorn ll_project.wsgi:application"

    hooks:
      build: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py collectstatic --noinput

    relationships:
      database: "db:postgresql"

mounts:
  "staticfiles":
    source: local
    source_path: staticfiles

services:
  db:
    type: postgresql:14

routes:
  "https://{default}/":
    type: upstream
    upstream: "app:http"
  "http://{default}/":
    type: redirect
    to: "https://{default}/"
